// <auto-generated />
using System;
using Aprs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aprs.Infrastructure.Migrations
{
    [DbContext(typeof(AprsDbContext))]
    partial class AprsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aprs.Domain.Entities.AprsPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("SymbolCode")
                        .HasColumnType("text");

                    b.Property<string>("SymbolTable")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .IsDescending();

                    b.HasIndex("Type");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("Aprs.Domain.Entities.AprsPacket", b =>
                {
                    b.OwnsOne("Aprs.Domain.ValueObjects.Callsign", "Destination", b1 =>
                        {
                            b1.Property<int>("AprsPacketId")
                                .HasColumnType("integer");

                            b1.Property<string>("BaseCallsign")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("dest_base");

                            b1.Property<int>("Ssid")
                                .HasColumnType("integer")
                                .HasColumnName("dest_ssid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("dest_callsign");

                            b1.HasKey("AprsPacketId");

                            b1.ToTable("Packets");

                            b1.WithOwner()
                                .HasForeignKey("AprsPacketId");
                        });

                    b.OwnsOne("Aprs.Domain.ValueObjects.Callsign", "Sender", b1 =>
                        {
                            b1.Property<int>("AprsPacketId")
                                .HasColumnType("integer");

                            b1.Property<string>("BaseCallsign")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("sender_base");

                            b1.Property<int>("Ssid")
                                .HasColumnType("integer")
                                .HasColumnName("sender_ssid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("sender_callsign");

                            b1.HasKey("AprsPacketId");

                            b1.HasIndex("Value");

                            b1.ToTable("Packets");

                            b1.WithOwner()
                                .HasForeignKey("AprsPacketId");
                        });

                    b.OwnsOne("Aprs.Domain.Entities.WeatherData", "Weather", b1 =>
                        {
                            b1.Property<int>("AprsPacketId")
                                .HasColumnType("integer");

                            b1.Property<int?>("Humidity")
                                .HasColumnType("integer")
                                .HasColumnName("wx_humidity");

                            b1.Property<int?>("Pressure")
                                .HasColumnType("integer")
                                .HasColumnName("wx_pressure");

                            b1.Property<int?>("Rain1h")
                                .HasColumnType("integer")
                                .HasColumnName("wx_rain_1h");

                            b1.Property<int?>("Rain24h")
                                .HasColumnType("integer")
                                .HasColumnName("wx_rain_24h");

                            b1.Property<int?>("RainMidnight")
                                .HasColumnType("integer")
                                .HasColumnName("wx_rain_midnight");

                            b1.Property<int?>("Temperature")
                                .HasColumnType("integer")
                                .HasColumnName("wx_temp");

                            b1.Property<int?>("WindDirection")
                                .HasColumnType("integer")
                                .HasColumnName("wx_wind_dir");

                            b1.Property<int?>("WindGust")
                                .HasColumnType("integer")
                                .HasColumnName("wx_wind_gust");

                            b1.Property<int?>("WindSpeed")
                                .HasColumnType("integer")
                                .HasColumnName("wx_wind_speed");

                            b1.HasKey("AprsPacketId");

                            b1.ToTable("Packets");

                            b1.WithOwner()
                                .HasForeignKey("AprsPacketId");
                        });

                    b.OwnsOne("Aprs.Domain.ValueObjects.GeoCoordinate", "Position", b1 =>
                        {
                            b1.Property<int>("AprsPacketId")
                                .HasColumnType("integer");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("AprsPacketId");

                            b1.HasIndex("Latitude");

                            b1.HasIndex("Longitude");

                            b1.ToTable("Packets");

                            b1.WithOwner()
                                .HasForeignKey("AprsPacketId");
                        });

                    b.Navigation("Destination");

                    b.Navigation("Position");

                    b.Navigation("Sender")
                        .IsRequired();

                    b.Navigation("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
